title: Rime·徐码·CJK全汉字拆分·三重注解·自定义常用字集
description: Rime·徐码·CJK全汉字拆分·三重注解·自定义常用字集
theme: just-the-docs

url: https://forfudan.github.io/

plugins:
  - jekyll-relative-links
  - jekyll-default-layout
  
relative_links:
  enabled: true
  collections: true