plugins:
  - jekyll-relative-links
  - jekyll-default-layout
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

title: Rime·徐码·CJK全汉字拆分·三重注解·自定义常用字集
theme: just-the-docs